FROM resin/rpi-raspbian:jessie as runtime-env

### Tools setup

RUN apt-get update && apt-get -y install sudo
RUN apt-get upgrade -y
RUN apt-get install gnupg gnupg2 -y
RUN echo "deb http://archive.raspberrypi.org/debian/ jessie main" >>/etc/apt/sources.list
RUN apt-get install -y wget
RUN apt-get install libraspberrypi-bin -y --allow-unauthenticated
RUN usermod -a -G video root

FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app
 
COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1-runtime-stretch-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./
COPY /assets/* ./
RUN chmod +777 /app/*.2.*

RUN useradd -ms /bin/bash moduleuser
#RUN chown moduleuser /dev/gpiomem
#RUN chmod g+rw /dev/gpiomem
#USER moduleuser

ENTRYPOINT ["dotnet", "Blink.dll"]